default_config:
discovery:
circadian_lighting:
homeassistant:
  customize: !include customize.yaml
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest
tts:
  - platform: google_translate
logger:
  default: warn
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
webostv: !include webos.yaml
yeelight: !include yeelight.yaml
sensor command_line: !include cmd_sensor.yaml
sensor template: !include template_sensor.yaml
switch template: !include template_switch.yaml
switch command_line: !include cmd_switch.yaml
recorder:
  purge_keep_days: 30
  exclude:
    entities:
     - sensor.network_throughput_in_eth0
     - sensor.network_throughput_out_eth0
     - sensor.int_internet_health
     - sensor.radarr_movies
     - sensor.sonarr_shows
     - sensor.pyload_speed
     - sensor.vnstat
sensor:
#  - platform: history_stats
#    name: Power Downtime
#    entity_id: device_tracker.front_gate_camera
#    state: 'off'
#    type: time
#    end: '{{ now()}}'
#    duration:
#      days: 30
  - platform: history_stats
    name: int_internet_health
    entity_id: binary_sensor.google_dns_ping
    state: 'on'
    type: ratio
    end: '{{ now()}}'
    duration: 00:05:00
#   - platform: rtorrent
#    url: 'http://127.0.0.1:8008/RPC2'
#    monitored_variables:
#      - 'current_status'
#      - 'download_speed'
#      - 'upload_speed'
#      - 'all_torrents'
#      - 'stopped_torrents'
#      - 'complete_torrents'
#      - 'uploading_torrents'
#      - 'downloading_torrents'
#      - 'active_torrents'
  - platform: pyload
    host: 127.0.0.1
    port: 7700
    name: PyLoad
    username: !secret pyload_user
    password: !secret pyload_pass
  - platform: qbittorrent
    name: qBt
    url: 'http://127.0.0.1:8080'
    username: !secret qbt_user
    password: !secret qbt_pass
#  - platform: qbittorrent
#    name: qBt 2
#    url: ''
#    username: 
#    password:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: disk_use_percent
        arg: /home/agneev
      - type: disk_use_percent
        arg: /merged
  - platform: tautulli
    api_key: !secret tautulli
    host: 127.0.0.1
    monitored_users:
      - agneev
  - platform: radarr
    host: 127.0.0.1
    api_key: !secret radarr
    days: 14
    monitored_conditions:
      - movies
      - upcoming
      - commands
#  - platform: netdata
#    host: 127.0.0.1
#    resources:
#      cpu_iowait:
#         data_group: system.cpu
#         element: iowait
#         icon: mdi:cpu-64-bit
#  - platform: netdata
#    host: 
#    resources:
#      remote_disk_space_left:
#        data_group: disk_space._
#        element: avail
#        icon: mdi:harddisk
switch:
  - platform: circadian_lighting
    disable_brightness_adjust: true
    lights_ct:
      - light.desk_light
    lights_rgb:
      - light.bedside_lamp
#emulated_hue:
#  listen_port: 80
#  expose_by_default: false
#  entities:
#    switch.lofi_beats:
#      name: Lo-Fi Beats
#    switch.lofi_beats2:
#      name: Lo-Fi Beats 2
device_tracker:
  - platform: netgear
    host: 10.0.0.1
    port: 80
    username: !secret netgear_user
    password: !secret netgear_pass
    new_device_defaults:
      track_new_devices: true
#weather:
#  - platform: darksky
#    api_key: !secret dark_sky
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
#telegram_bot:
#  - platform: polling
#    api_key: !secret telegram
#    allowed_chat_ids:
#      - !secret telegram_chat_id
#notify:
#  - name: telegram_hassio
#    platform: telegram
#    chat_id: !secret telegram_chat_id
cloud:
  alexa:
    filter:
      include_entities:
        - switch.lofi_beats
        - switch.lofi_beats2
        - switch.jazz_radio
        - media_player.bedroom_tv
homekit:
  name: HA Bridge
  filter:
    include_entities:
      - switch.adguard_protection
      - switch.lofi_beats
      - switch.lofi_beats2
      - switch.jazz_radio
      - sensor.internet_health
      - light.bedside_lamp_nightlight
  entity_config:
    switch.adguard_protection:
      name: AdGuard
    light.bedside_lamp_nightlight:
      name: Night Lamp